movie_library/routes.py
from dataclasses import asdict
import datetime
import uuid
import functools
from flask import Blueprint, current_app, render_template, session, request, redirect, url_for, flash
from movie_library.forms import MovieForm, ExtendedMovieForm, RegisterForm, LoginForm
from movie_library.models import Movie, User
from passlib.hash import pbkdf2_sha256

pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


#login decorator, checks if there is an email present in the session, if not redirects to login page
def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))
    
        return route(*args, **kwargs)
    return route_wrapper

#def get_movie_collection():
#    with current_app.app_context():
#        moviedb = current_app.db.movie
####################################### 
#can only access current_app in application context, would have to do this then call moviedb = get_movie_collection() in each route
#would be worthwhile if i had more routes

@pages.route("/")
@login_required
def index():
    #find({}) grabs all
    #find_one(...) returns a SINGLE object not a CURSOR which is what find(..) returns
    user_data = current_app.db.user.find_one({"email": session["email"]})
    user = User(**user_data)
    
    #finding _id that is "$in" user's movie list (user.movies) (created above in the user object when we get session email)
    movie_data = current_app.db.movie.find({"_id": {"$in": user.movies}}) 
    movies = [Movie(**data) for data in movie_data]

    return render_template(
        "index.html",
        title="Movies Watchlist",
        movie_data = movies
    )


@pages.route("/register", methods=["GET", "POST"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))
    
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            _id = uuid.uuid4().hex,
            email = form.email.data,
            password = pbkdf2_sha256.hash(form.password.data)
        )

        current_app.db.user.insert_one(asdict(user))
        flash("Successfully Registered!", "success")

        return redirect(url_for(".login"))

    return render_template("register.html", title= "Movies Watchlist - Register", form=form)


@pages.route("/login", methods=["GET", "POST"])
def login(): 
    if session.get("email"):
        return redirect(url_for(".index"))
    
    form = LoginForm()
    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": form.email.data})
        if not user_data:
            #if this flashes, means that user has not registered or email incorrect 
            flash("Incorrect login information", category="danger")
            return redirect(url_for(".login"))
        
        user = User(**user_data)

        #hash login form password (arg1) and compare to user password in db (arg2)
        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))
        
        #if this flashes, means that password was incorrect (email exists) 
        flash("Incorrect login information", category="danger")

    return render_template("login.html", title="Movie Watchlist - Login", form = form)


@pages.route("/logout")
def logout():
    theme = session.get("theme")
    session.clear()
    session["theme"] = theme

    return redirect(url_for(".login"))



@pages.route("/add", methods = ["GET", "POST"])
@login_required
def add_movie():
    #in Flask-WTF, when you create an instance of a form class, you typically do not need to pass any arguments to it directly
    form = MovieForm()

    #using validate_on_submit() if there are errors (ie missing fields) it will update form and be sent to be rendered
    if form.validate_on_submit():
        movie = Movie(_id = uuid.uuid4().hex,
            title= form.title.data,
            director= form.director.data,
            year= form.year.data
        )

        #create 'movie' collection in the database.
        #MAKE SURE TO CONVERT movie obj to dictionary to be BSON compatible
        current_app.db.movie.insert_one(asdict(movie))
        
        #ADD TO USER'S MOVIE LIST
        current_app.db.user.update_one(
            {"_id": session["user_id"]}, {"$push": {"movies": movie._id}}
        )
        #checking if movie was added
        if current_app.db.movie.find_one(asdict(movie)):
            print(f"movie now exists in db: '{current_app.db.movie}'")

        return redirect(url_for('.index'))

    return render_template("new_movie.html", title="Movies Watchlist - Add Movie", form=form)

#Flask routing, the angle brackets < > are used to indicate variable parts of the URL
@pages.get("/movie/<string:_id>")
def movie(_id: str):
    #can add 404 check (if not ... : abort(404))
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))
    return render_template("movie_details.html", movie=movie)


@pages.get("/movie/<string:_id>/rate")
@login_required
def rate_movie(_id):
    rating = int(request.args.get('rating'))
    current_app.db.movie.update_one({"_id": _id}, {"$set": {"rating":rating}})
    
    return redirect(url_for(".movie", _id=_id))


@pages.get("/movie/<string:_id>/watch")
@login_required
def watch_today(_id):
    current_app.db.movie.update_one({"_id": _id}, {"$set": {"last_watched":datetime.datetime.today()}})

    return redirect(url_for(".movie", _id=_id))


                    #no emptyspace
@pages.route("/edit/<string:_id>", methods= ["GET", "POST"])
@login_required
def edit_movie(_id: str):
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))
    form = ExtendedMovieForm(obj=movie)
    if form.validate_on_submit():
        movie.cast = form.cast.data
        movie.series = form.series.data
        movie.tags = form.tags.data
        movie.description = form.description.data
        movie.video_link = form.video_link.data

        #convert all the modified and original movie data into a dict and update the entry with matching _id
        current_app.db.movie.update_one({"_id": movie._id}, {"$set": asdict(movie)})
        return redirect(url_for(".movie", _id=movie._id))
    
    return render_template("movie_form.html", movie=movie, form=form)




@pages.get("/toggle-theme")
def toggle_theme():
    theme = session.get('theme')
    if theme == "dark":
        session["theme"] = "light"
    else:
        session["theme"] = "dark"
    
    return redirect(request.args.get('current_page'))

movie_library/templates/macros/fields.html
{% macro render_text_field(field) %}
<div class="form__group">
    {{field.label(class_= "form__label")}}
    {{field(class_="form__field")}}

    {% for error in field.errors %}
        <span class="form__error">{{error}}</span>
    {% endfor %}
</div>
{% endmacro %}

{% macro render_area_field(field) %}
<div class="form__group">
    {{field.label(class_= "form__label")}}
    {{field(rows=4, class_="form__field", style="resize: none")}}

    {% for error in field.errors %}
        <span class="form__error">{{error}}</span>
    {% endfor %}
</div>
{% endmacro %}

movie_library/templates/macros/footer.html
{% macro footer() %}
<footer class="footer">
    <small>Copyright &copy;2024. Movies Watchlist.</small>
</footer>
{% endmacro %}

movie_library/templates/macros/nav.html
{% from "macros/svgs.html" import sun, moon %}

{% macro header(email,theme) %}

<header class="header">
    <div class="nav-container">
        <a href="{{url_for('pages.index')}}" class="header__logo">
            <svg xmlns="http://www.w3.org/2000/svg" class="logo__icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z" />
              </svg>    
            <span class="logo__name">Watchlist</span>
        </a>
        <nav class="nav">
            {% if not email %}
                <a href="{{url_for('pages.login')}}" class="nav__link {{'nav__link--active' if request.path==url_for('pages.register')}}">
                    <span class="nav__item">Log in</span>
                </a>
                <a href="{{url_for('pages.register')}}" class="nav__link {{'nav__link--active' if request.path==url_for('pages.register')}}">
                    <span class="nav__item">Register</span>
                </a>

            {% else %}
                <a href="{{url_for('pages.index')}}" class="nav__link {{'nav__link--active' if request.path==url_for('pages.index')}}">
                    <span class="nav__item">Movies</span>
                </a>
                <a href="{{url_for('pages.logout')}}" class="nav__link">
                    <span class="nav__item">Log out</span>
                </a>

            {% endif %}
            <!--url_for('<function_name>')-->
            <a href="{{url_for('pages.toggle_theme', current_page=request.path)}}" class="nav__link">
                <span class="nav__item">
                    {% if theme == "dark" %}
                        {{sun("nav__icon")}}
                    {% else %}
                        {{moon("nav__icon")}}
                    {% endif %}
                </span>
            </a>
        </nav>
    </div>
</header>
{% endmacro %}

movie_library/templates/macros/svgs.html
{% macro star(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
</svg>
{% endmacro %}

{% macro pencil(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
</svg>
{% endmacro %}

{% macro moon(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
</svg>
{% endmacro %}

{% macro sun(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
</svg>
{% endmacro %}